PEAK OVERLAPS between ATF4 data and the Basal and Stress induced conditions in Liver (26960794)

In [1]:
import pandas as pd
rna_seq = pd.read_table('ATF4_RNAseq/WT_and_KO_Tmc_treatment_GSE76771/GSE76771_ALL_gene_expression.txt', header=4)
rna_seq

/scratch/271641.1.ood/ipykernel_589641/738613747.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  rna_seq = pd.read_table('ATF4_RNAseq/WT_and_KO_Tmc_treatment_GSE76771/GSE76771_ALL_gene_expression.txt', header=4)

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
0,XLOC_000001,XLOC_000001,Mrpl15,chr1:4763266-4776053,q1,q2,OK,37.431800,22.2465,27.238000,21.3535,-0.750685,-0.99303,0.08845,0.233153,no,NaN
1,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q1,q2,OK,129.649000,60.7268,93.617800,56.7086,-1.0942,-3.21376,0.00005,0.000396,yes,NaN
2,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q1,q2,OK,11.403900,35.5800,8.405530,22.7315,1.64154,4.81123,0.00005,0.000396,yes,NaN
3,XLOC_000004,XLOC_000004,Atp6v1h,chr1:5073174-5152695,q1,q2,OK,43.760900,42.6246,37.858200,47.6802,-0.0379559,-0.113404,0.84135,0.933306,no,NaN
4,XLOC_000005,XLOC_000005,Oprk1,chr1:5578573-5596214,q1,q2,NOTEST,0.004171,0.0000,0.003107,0.0000,#NAME?,0,1.00000,1.000000,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162649,XLOC_027107,XLOC_027107,Gm20865,chrY_random:48242250-48243108,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162650,XLOC_027108,XLOC_027108,Gm20747,chrY_random:48319177-48321522,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162651,XLOC_027109,XLOC_027109,Ssty1,chrY_random:48388360-48390745,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162652,XLOC_027110,XLOC_027110,Gm20823,chrY_random:50814753-50817087,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162653,XLOC_027111,XLOC_027111,Gm20736,chrY_random:52063164-52089373,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN

In [2]:
sig_rna = rna_seq[rna_seq['significant'] == 'yes']
sig_rna = sig_rna[sig_rna['gene']!= '']
sig_rna = sig_rna[sig_rna['gene']!= '-']
sig_rna

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
1,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q1,q2,OK,129.64900,60.72680,93.61780,56.7086,-1.0942,-3.21376,0.00005,0.000396,yes,NaN
2,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q1,q2,OK,11.40390,35.58000,8.40553,22.7315,1.64154,4.81123,0.00005,0.000396,yes,NaN
5,XLOC_000006,XLOC_000006,Rb1cc1,chr1:6202274-6266498,q1,q2,OK,11.87730,24.00940,9.50791,18.6403,1.0154,2.98767,0.00005,0.000396,yes,NaN
8,XLOC_000009,XLOC_000009,Pcmtd1,chr1:7079000-7163709,q1,q2,OK,32.17730,19.94960,29.46680,18.4394,-0.689684,-2.0965,0.00015,0.001079,yes,NaN
9,XLOC_000010,XLOC_000010,Rrs1,chr1:9535488-9537536,q1,q2,OK,11.50620,24.09370,13.20510,25.4585,1.06625,2.99521,0.00005,0.000396,yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162406,XLOC_026864,XLOC_026864,"Mbtps2,Yy2",chrX:153985753-154036647,q3,q4,OK,3.46128,6.58956,NaN,NaN,0.928876,2.35238,0.00025,0.001706,yes,0.279619684
162410,XLOC_026868,XLOC_026868,Cdkl5,chrX:157205944-157432621,q3,q4,OK,1.12592,1.84242,NaN,NaN,0.710499,1.65925,0.00315,0.015562,yes,0.213881106
162426,XLOC_026884,XLOC_026884,Ofd1,chrX:162827964-162891234,q3,q4,OK,1.38635,3.54952,NaN,NaN,1.35633,2.60375,0.00010,0.000747,yes,0.408296741
162434,XLOC_026892,XLOC_026892,Prps2,chrX:163784264-163820675,q3,q4,OK,8.19667,4.08075,NaN,NaN,-1.0062,-2.65015,0.00005,0.000396,yes,-0.302897461
162438,XLOC_026896,XLOC_026896,Hccs,chrX:165749462-165758310,q3,q4,OK,8.07035,12.84400,NaN,NaN,0.670397,1.79676,0.00225,0.011651,yes,0.201807927

In [3]:
# Filter the rows where the 'gene' column contains 'Mar' or 'Sep'
date_genes = sig_rna[sig_rna['gene'].str.contains(r'\b(Mar|Sep)\b', na=False, regex=True)]

# Extract the 'gene' column as a list
date_gene_list = date_genes['gene'].tolist()

print(date_gene_list)

['2-Sep', '1-Mar', '9-Sep', '6-Mar', '2-Mar', '3-Mar', '5-Mar', '11-Sep', '8-Sep', '2-Sep', '1-Mar', '9-Sep', '6-Mar', '3-Mar', '5-Mar', '11-Sep', '2-Sep', '9-Mar', '8-Sep', '9-Sep', '2-Mar', '3-Mar', '5-Mar', '11-Sep', '8-Mar', '6-Mar', '11-Sep', '2-Sep', '9-Sep', '3-Mar', '5-Mar', '7-Mar', '11-Sep', '7-Sep']

/scratch/271641.1.ood/ipykernel_589641/2628799386.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  date_genes = sig_rna[sig_rna['gene'].str.contains(r'\b(Mar|Sep)\b', na=False, regex=True)]

In [4]:
# Mapping of month abbreviations to full names
month_mapping = {
    'Mar': 'March','Sep': 'Sept'
}

# Function to rename genes
def rename_gene(gene_name):
    if isinstance(gene_name, str):
        parts = gene_name.split('-', 1)  # Split only on the first '-'
        if len(parts) == 2:
            number, month_abbr = parts
            month_full = month_mapping.get(month_abbr, month_abbr)  # Use the mapping or keep the abbreviation
            return f"{month_full}{number}"
    return gene_name  # Return the original name if not in the 'number-Month' format or if not a string

# Apply the function to the 'gene' column
sig_rna['gene'] = sig_rna['gene'].apply(rename_gene)

# Display the updated DataFrame
print(sig_rna)

            test_id      gene_id        gene                     locus  \
1       XLOC_000002  XLOC_000002      Lypla1      chr1:4797973-4836816
2       XLOC_000003  XLOC_000003       Tcea1      chr1:4847774-4887990
5       XLOC_000006  XLOC_000006      Rb1cc1      chr1:6202274-6266498
8       XLOC_000009  XLOC_000009      Pcmtd1      chr1:7079000-7163709
9       XLOC_000010  XLOC_000010        Rrs1      chr1:9535488-9537536
...             ...          ...         ...                       ...
162406  XLOC_026864  XLOC_026864  Mbtps2,Yy2  chrX:153985753-154036647
162410  XLOC_026868  XLOC_026868       Cdkl5  chrX:157205944-157432621
162426  XLOC_026884  XLOC_026884        Ofd1  chrX:162827964-162891234
162434  XLOC_026892  XLOC_026892       Prps2  chrX:163784264-163820675
162438  XLOC_026896  XLOC_026896        Hccs  chrX:165749462-165758310

       sample_1 sample_2 status    value_1   value_2   Value 3  Value 4  \
1            q1       q2     OK  129.64900  60.72680  93.61780  56.7086
2            q1       q2     OK   11.40390  35.58000   8.40553  22.7315
5            q1       q2     OK   11.87730  24.00940   9.50791  18.6403
8            q1       q2     OK   32.17730  19.94960  29.46680  18.4394
9            q1       q2     OK   11.50620  24.09370  13.20510  25.4585
...         ...      ...    ...        ...       ...       ...      ...
162406       q3       q4     OK    3.46128   6.58956       NaN      NaN
162410       q3       q4     OK    1.12592   1.84242       NaN      NaN
162426       q3       q4     OK    1.38635   3.54952       NaN      NaN
162434       q3       q4     OK    8.19667   4.08075       NaN      NaN
162438       q3       q4     OK    8.07035  12.84400       NaN      NaN

       log2(fold_change) test_stat  p_value   q_value significant  \
1                -1.0942  -3.21376  0.00005  0.000396         yes
2                1.64154   4.81123  0.00005  0.000396         yes
5                 1.0154   2.98767  0.00005  0.000396         yes
8              -0.689684   -2.0965  0.00015  0.001079         yes
9                1.06625   2.99521  0.00005  0.000396         yes
...                  ...       ...      ...       ...         ...
162406          0.928876   2.35238  0.00025  0.001706         yes
162410          0.710499   1.65925  0.00315  0.015562         yes
162426           1.35633   2.60375  0.00010  0.000747         yes
162434           -1.0062  -2.65015  0.00005  0.000396         yes
162438          0.670397   1.79676  0.00225  0.011651         yes

         Unnamed: 16
1                NaN
2                NaN
5                NaN
8                NaN
9                NaN
...              ...
162406   0.279619684
162410   0.213881106
162426   0.408296741
162434  -0.302897461
162438   0.201807927

[21338 rows x 17 columns]

In [76]:
# Filter the DataFrame for rows where 'sample_1' is 'q1' and 'sample_2' is 'q2'
filtered_df = sig_rna[(sig_rna['sample_1'] == 'q3') & (sig_rna['sample_2'] == 'q4')]

filtered_df

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
135546,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q3,q4,OK,93.61780,56.70860,NaN,NaN,-0.723214,-2.11651,0.00030,0.002003,yes,-0.217709505
135547,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q3,q4,OK,8.40553,22.73150,NaN,NaN,1.43528,4.04783,0.00005,0.000396,yes,0.432062992
135550,XLOC_000006,XLOC_000006,Rb1cc1,chr1:6202274-6266498,q3,q4,OK,9.50791,18.64030,NaN,NaN,0.971226,2.86948,0.00005,0.000396,yes,0.292367836
135553,XLOC_000009,XLOC_000009,Pcmtd1,chr1:7079000-7163709,q3,q4,OK,29.46680,18.43940,NaN,NaN,-0.676303,-2.02869,0.00050,0.003147,yes,-0.20358619
135554,XLOC_000010,XLOC_000010,Rrs1,chr1:9535488-9537536,q3,q4,OK,13.20510,25.45850,NaN,NaN,0.947046,2.69432,0.00005,0.000396,yes,0.285091117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162406,XLOC_026864,XLOC_026864,"Mbtps2,Yy2",chrX:153985753-154036647,q3,q4,OK,3.46128,6.58956,NaN,NaN,0.928876,2.35238,0.00025,0.001706,yes,0.279619684
162410,XLOC_026868,XLOC_026868,Cdkl5,chrX:157205944-157432621,q3,q4,OK,1.12592,1.84242,NaN,NaN,0.710499,1.65925,0.00315,0.015562,yes,0.213881106
162426,XLOC_026884,XLOC_026884,Ofd1,chrX:162827964-162891234,q3,q4,OK,1.38635,3.54952,NaN,NaN,1.35633,2.60375,0.00010,0.000747,yes,0.408296741
162434,XLOC_026892,XLOC_026892,Prps2,chrX:163784264-163820675,q3,q4,OK,8.19667,4.08075,NaN,NaN,-1.0062,-2.65015,0.00005,0.000396,yes,-0.302897461
162438,XLOC_026896,XLOC_026896,Hccs,chrX:165749462-165758310,q3,q4,OK,8.07035,12.84400,NaN,NaN,0.670397,1.79676,0.00225,0.011651,yes,0.201807927

In [77]:
# Remove entries with NaN in the 'gene' column
sig_rna_cleaned = filtered_df.dropna(subset=['gene'])

# Display the cleaned DataFrame
sig_rna_cleaned

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
135546,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q3,q4,OK,93.61780,56.70860,NaN,NaN,-0.723214,-2.11651,0.00030,0.002003,yes,-0.217709505
135547,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q3,q4,OK,8.40553,22.73150,NaN,NaN,1.43528,4.04783,0.00005,0.000396,yes,0.432062992
135550,XLOC_000006,XLOC_000006,Rb1cc1,chr1:6202274-6266498,q3,q4,OK,9.50791,18.64030,NaN,NaN,0.971226,2.86948,0.00005,0.000396,yes,0.292367836
135553,XLOC_000009,XLOC_000009,Pcmtd1,chr1:7079000-7163709,q3,q4,OK,29.46680,18.43940,NaN,NaN,-0.676303,-2.02869,0.00050,0.003147,yes,-0.20358619
135554,XLOC_000010,XLOC_000010,Rrs1,chr1:9535488-9537536,q3,q4,OK,13.20510,25.45850,NaN,NaN,0.947046,2.69432,0.00005,0.000396,yes,0.285091117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162406,XLOC_026864,XLOC_026864,"Mbtps2,Yy2",chrX:153985753-154036647,q3,q4,OK,3.46128,6.58956,NaN,NaN,0.928876,2.35238,0.00025,0.001706,yes,0.279619684
162410,XLOC_026868,XLOC_026868,Cdkl5,chrX:157205944-157432621,q3,q4,OK,1.12592,1.84242,NaN,NaN,0.710499,1.65925,0.00315,0.015562,yes,0.213881106
162426,XLOC_026884,XLOC_026884,Ofd1,chrX:162827964-162891234,q3,q4,OK,1.38635,3.54952,NaN,NaN,1.35633,2.60375,0.00010,0.000747,yes,0.408296741
162434,XLOC_026892,XLOC_026892,Prps2,chrX:163784264-163820675,q3,q4,OK,8.19667,4.08075,NaN,NaN,-1.0062,-2.65015,0.00005,0.000396,yes,-0.302897461
162438,XLOC_026896,XLOC_026896,Hccs,chrX:165749462-165758310,q3,q4,OK,8.07035,12.84400,NaN,NaN,0.670397,1.79676,0.00225,0.011651,yes,0.201807927

In [78]:
sig_rna_cleaned['gene']

135546        Lypla1
135547         Tcea1
135550        Rb1cc1
135553        Pcmtd1
135554          Rrs1
             ...
162406    Mbtps2,Yy2
162410         Cdkl5
162426          Ofd1
162434         Prps2
162438          Hccs
Name: gene, Length: 4665, dtype: object

In [93]:
# Use your annotated (.txt) file here
atf4_aad = pd.read_table('Mito_stress_treatment/Amino_acid_deprivation/ATF4/results/annotation/ATF4_AAD_annotated.txt')
atf4_aad['SYMBOL']

0            Gm26206
1      A830018L16Rik
2            Gm17644
3            Gm17644
4            Gm17644
           ...
653           Erdr1x
654           Erdr1x
655           Erdr1x
656           Erdr1x
657           Erdr1x
Name: SYMBOL, Length: 658, dtype: object

In [94]:
genes_to_check = sig_rna_cleaned['gene'].tolist()
filtered_genes_new = atf4_aad[atf4_aad['SYMBOL'].isin(sig_rna_cleaned['gene'])]
filtered_genes_new

,seqnames,start,end,width,strand,V4,V5,V6,V7,V8,...,geneStart,geneEnd,geneLength,geneStrand,geneId,transcriptId,distanceToTSS,ENSEMBL,SYMBOL,GENENAME
8,chr1,36365185,36365267,83,*,ATF4_AAD_peak_692,54,.,6.55785,9.56596,...,36356108,36357213,1106,1,214855,ENSMUST00000141121.2,9077,ENSMUSG00000037447,Arid5a,AT-rich interaction domain 5A
13,chr1,44650803,44650841,39,*,ATF4_AAD_peak_700,68,.,7.28650,10.99650,...,44591757,44747792,156036,1,70676,ENSMUST00000161066.8,59046,ENSMUSG00000056870,Gulp1,"GULP, engulfment adaptor PTB domain containing 1"
16,chr1,45905682,45905724,43,*,ATF4_AAD_peak_703,41,.,5.82920,8.18088,...,45861718,45862776,1059,1,73674,ENSMUST00000186651.2,43964,ENSMUSG00000025995,Wdr75,WD repeat domain 75
18,chr1,58758511,58758558,48,*,ATF4_AAD_peak_707,83,.,8.01514,12.46810,...,58752476,58794324,41849,1,12633,ENSMUST00000069333.8,6035,ENSMUSG00000026031,Cflar,CASP8 and FADD-like apoptosis regulator
24,chr1,74759123,74759166,44,*,ATF4_AAD_peak_716,128,.,10.20110,17.09710,...,74752733,74777051,24319,1,104086,ENSMUST00000027356.7,6390,ENSMUSG00000026170,Cyp27a1,"cytochrome P450, family 27, subfamily a, polyp..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,chr9,71838808,71838845,38,*,ATF4_AAD_peak_2855,41,.,5.82920,8.18088,...,71791719,71829992,38274,2,21406,ENSMUST00000184029.2,-8816,ENSMUSG00000032228,Tcf12,transcription factor 12
502,chr9,103078663,103078700,38,*,ATF4_AAD_peak_2868,28,.,5.10055,6.84649,...,103066289,103079328,13040,2,20818,ENSMUST00000163567.8,628,ENSMUSG00000032553,Srprb,"signal recognition particle receptor, B subunit"
504,chr9,108396325,108396362,38,*,ATF4_AAD_peak_2870,54,.,6.55785,9.56596,...,108394822,108406094,11273,1,69232,ENSMUST00000192819.2,1503,ENSMUSG00000006673,Qrich1,glutamine-rich 1
507,chrX,9771426,9771467,42,*,ATF4_AAD_peak_2947,54,.,6.55785,9.56596,...,9751861,9860782,108922,1,236643,ENSMUST00000086165.4,19565,ENSMUSG00000054453,Sytl5,synaptotagmin-like 5
520,chrX,139445506,139445743,238,*,ATF4_AAD_peak_2977,113,.,9.47244,15.52120,...,139440277,139443936,3660,2,14605,ENSMUST00000055738.12,-1570,ENSMUSG00000031431,Tsc22d3,"TSC22 domain family, member 3"

In [81]:
filtered_genes_new.to_csv('ATF4_RNAseq/WT_and_KO_Tmc_treatment_GSE76771/ER_overlaps/ATF4_ER_peaks_overlap_with_KO_vs_KO-TT.bed', sep = '\t')

PEAK OVERLAPS between ATF4 data and the mTORC1 activation of ATF4 (33646118)

In [99]:
atf4_tuni = pd.read_table('ATF4_RNAseq/mTORC1_GSE158605/ATF4_insulin_Rapamycin.txt')
atf4_tuni

     Unnamed: 0               genes   Symbol  entrez     logFC     adj.P.Val
0             1  ENSMUSG00000024359    Hspa9   15526 -0.071599  3.579839e-01
1             2  ENSMUSG00000026456   Cyb5r1   72017 -0.223558  4.578298e-02
2             3  ENSMUSG00000023883    Phf10   72057 -0.007964  9.520628e-01
3             4  ENSMUSG00000039518     Cdsn  386463 -0.307763  1.333633e-01
4             5  ENSMUSG00000025403    Shmt2  108037 -0.230471  7.143343e-02
..          ...                 ...      ...     ...       ...           ...
107         108  ENSMUSG00000046516    Cox17   12856 -0.260391  1.977019e-01
108         109  ENSMUSG00000026275   Ppp1r7   66385  0.030580  7.944266e-01
109         110  ENSMUSG00000071359    Tbpl1  237336  0.123369  2.335729e-01
110         111  ENSMUSG00000025993  Slc40a1   53945  0.277958  5.917686e-01
111         112  ENSMUSG00000047139    Cd24a   12484  0.612392  8.503610e-07

[112 rows x 6 columns]

In [100]:
atf4_tuni['Symbol']

0        Hspa9
1       Cyb5r1
2        Phf10
3         Cdsn
4        Shmt2
        ...
107      Cox17
108     Ppp1r7
109      Tbpl1
110    Slc40a1
111      Cd24a
Name: Symbol, Length: 112, dtype: object

In [101]:
filtered_genes_new = atf4_aad[atf4_aad['SYMBOL'].isin(atf4_tuni['Symbol'])]
filtered_genes_new

,seqnames,start,end,width,strand,V4,V5,V6,V7,V8,...,geneStart,geneEnd,geneLength,geneStrand,geneId,transcriptId,distanceToTSS,ENSEMBL,SYMBOL,GENENAME
57,chr10,59788666,59788725,60,*,ATF4_AAD_peak_843,54,.,6.55785,9.56596,...,59785491,59787656,2166,2,74747,ENSMUST00000020308.5,-1010,ENSMUSG00000020108,Ddit4,DNA-damage-inducible transcript 4
58,chr10,59788768,59788805,38,*,ATF4_AAD_peak_844,54,.,6.55785,9.56596,...,59785491,59787656,2166,2,74747,ENSMUST00000020308.5,-1112,ENSMUSG00000020108,Ddit4,DNA-damage-inducible transcript 4
76,chr10,127357617,127357918,302,*,ATF4_AAD_peak_868,97,.,8.74379,13.97730,...,127356337,127358233,1897,2,108037,ENSMUST00000217682.2,315,ENSMUSG00000025403,Shmt2,serine hydroxymethyltransferase 2 (mitochondrial)
101,chr11,96713561,96713608,48,*,ATF4_AAD_peak_1136,41,.,5.82920,8.18088,...,96712172,96713551,1380,2,18023,ENSMUST00000134951.2,-10,ENSMUSG00000038615,Nfe2l1,"nuclear factor, erythroid derived 2,-like 1"
129,chr12,84034226,84034385,160,*,ATF4_AAD_peak_1179,193,.,13.11570,23.68130,...,84034635,84040647,6013,1,171210,ENSMUST00000021649.8,-250,ENSMUSG00000021226,Acot2,acyl-CoA thioesterase 2
177,chr14,55777543,55777688,146,*,ATF4_AAD_peak_1308,68,.,7.28650,10.99650,...,55777723,55787474,9752,1,74551,ENSMUST00000048781.4,-35,ENSMUSG00000040618,Pck2,phosphoenolpyruvate carboxykinase 2 (mitochond...
232,chr17,46382304,46382341,38,*,ATF4_AAD_peak_1478,28,.,5.10055,6.84649,...,46329469,46343295,13827,2,22339,ENSMUST00000142351.9,-39009,ENSMUSG00000023951,Vegfa,vascular endothelial growth factor A
260,chr19,15902490,15902554,65,*,ATF4_AAD_peak_1541,68,.,7.28650,10.99650,...,15882042,15902423,20382,2,107272,ENSMUST00000025542.10,-67,ENSMUSG00000024640,Psat1,phosphoserine aminotransferase 1
262,chr19,27193999,27194125,127,*,ATF4_AAD_peak_1544,54,.,6.55785,9.56596,...,27193884,27227155,33272,1,22359,ENSMUST00000164509.8,115,ENSMUSG00000024924,Vldlr,very low density lipoprotein receptor
263,chr19,27194185,27194252,68,*,ATF4_AAD_peak_1545,97,.,8.74379,13.97730,...,27194420,27212256,17837,1,22359,ENSMUST00000164746.8,-168,ENSMUSG00000024924,Vldlr,very low density lipoprotein receptor
291,chr2,106804873,106804922,50,*,ATF4_AAD_peak_1612,83,.,8.01514,12.46810,...,106792872,106804769,11898,2,212772,ENSMUST00000028536.13,-104,ENSMUSG00000027122,Arl14ep,ADP-ribosylation factor-like 14 effector protein
292,chr2,106805044,106805105,62,*,ATF4_AAD_peak_1613,17,.,4.37190,5.56942,...,106792872,106804769,11898,2,212772,ENSMUST00000028536.13,-275,ENSMUSG00000027122,Arl14ep,ADP-ribosylation factor-like 14 effector protein
294,chr2,119181289,119181682,394,*,ATF4_AAD_peak_1617,280,.,16.75890,32.43420,...,119181710,119184862,3153,1,69065,ENSMUST00000028780.4,-28,ENSMUSG00000027313,Chac1,"ChaC, cation transport regulator 1"
316,chr3,50398020,50398163,144,*,ATF4_AAD_peak_1690,54,.,6.55785,9.56596,...,49846975,50398063,551089,2,26570,ENSMUST00000194462.6,0,ENSMUSG00000027737,Slc7a11,solute carrier family 7 (cationic amino acid t...
357,chr4,132237240,132237277,38,*,ATF4_AAD_peak_1781,17,.,4.37190,5.56942,...,132219343,132237812,18470,2,230784,ENSMUST00000030724.9,535,ENSMUSG00000028893,Sesn2,sestrin 2
358,chr4,132241295,132241343,49,*,ATF4_AAD_peak_1782,41,.,5.82920,8.18088,...,132219343,132237812,18470,2,230784,ENSMUST00000030724.9,-3483,ENSMUSG00000028893,Sesn2,sestrin 2
359,chr4,132241388,132241451,64,*,ATF4_AAD_peak_1783,28,.,5.10055,6.84649,...,132219343,132237812,18470,2,230784,ENSMUST00000030724.9,-3576,ENSMUSG00000028893,Sesn2,sestrin 2
404,chr5,148356037,148356142,106,*,ATF4_AAD_peak_2493,128,.,10.20110,17.09710,...,148264220,148336714,72495,2,11987,ENSMUST00000048116.15,-19323,ENSMUSG00000041313,Slc7a1,solute carrier family 7 (cationic amino acid t...
405,chr6,7693024,7693113,90,*,ATF4_AAD_peak_2503,41,.,5.82920,8.18088,...,7682273,7693110,10838,2,27053,ENSMUST00000126303.8,0,ENSMUSG00000029752,Asns,asparagine synthetase
406,chr6,7693182,7693237,56,*,ATF4_AAD_peak_2504,128,.,10.20110,17.09710,...,7675169,7693254,18086,2,27053,ENSMUST00000031766.12,17,ENSMUSG00000029752,Asns,asparagine synthetase
418,chr6,83294118,83294270,153,*,ATF4_AAD_peak_2608,97,.,8.74379,13.97730,...,83283384,83294535,11152,2,17768,ENSMUST00000203847.3,265,ENSMUSG00000005667,Mthfd2,methylenetetrahydrofolate dehydrogenase (NAD+ ...
439,chr7,34749945,34749991,47,*,ATF4_AAD_peak_2640,83,.,8.01514,12.46810,...,34749740,34755365,5626,2,12611,ENSMUST00000070191.10,5374,ENSMUSG00000056216,Cebpg,CCAAT/enhancer binding protein gamma
440,chr7,34750174,34750237,64,*,ATF4_AAD_peak_2641,41,.,5.82920,8.18088,...,34749740,34755365,5626,2,12611,ENSMUST00000070191.10,5128,ENSMUSG00000056216,Cebpg,CCAAT/enhancer binding protein gamma
466,chr8,27751224,27751326,103,*,ATF4_AAD_peak_2780,83,.,8.01514,12.46810,...,27750357,27766702,16346,1,13685,ENSMUST00000033880.7,867,ENSMUSG00000031490,Eif4ebp1,eukaryotic translation initiation factor 4E bi...
467,chr8,27751420,27751457,38,*,ATF4_AAD_peak_2781,54,.,6.55785,9.56596,...,27750357,27766702,16346,1,13685,ENSMUST00000033880.7,1063,ENSMUSG00000031490,Eif4ebp1,eukaryotic translation initiation factor 4E bi...
482,chr8,122625252,122625421,170,*,ATF4_AAD_peak_2832,97,.,8.74379,13.97730,...,122615113,122623241,8129,2,20539,ENSMUST00000183015.2,-2011,ENSMUSG00000040010,Slc7a5,solute carrier family 7 (cationic amino acid t...

In [102]:
filtered_genes_new.to_csv('ATF4_RNAseq/mTORC1_GSE158605/AAD/ATF4_AAD_from_mTORC1_ATF4-IR.bed', sep = '\t')

In [118]:
import pandas as pd

# Load the bed file
df = pd.read_csv('ATF4_RNAseq/WT_and_KO_Tmc_treatment_LIVER_GSE76771/ER_overlaps/ATF4_ER_peaks_overlap_with_WT-TT_vs_KO.bed', sep='\t', header=None)

# Drop the first column (index 0)
df = df.drop(columns=[0])

# Save the result
df.to_csv('ATF4_RNAseq/WT_and_KO_Tmc_treatment_LIVER_GSE76771/ER_overlaps/ATF4_ER_peaks_overlap_with_WT-TT_vs_KO.bed', sep='\t', header=False, index=False)

PEAK OVERLAPS between ATF4 data and the Multiomics paper (28566324)

In [122]:
# Load the gene list
with open('ATF4_RNAseq/Multiomics/Multiomics_DE_genes.txt') as f:
    genes = set(line.strip().lower() for line in f)

# Check the genes in the file and save to a .bed file
with open('Mito_stress_treatment/ER_stress/ATF4/results/annotation/ATF4_WT_Tmc_vs_ATF4_KO_Tmc_annotated.txt') as f, open('ATF4_RNAseq/Multiomics/ATF4_ER_overlaps_with_DEgenes_Multiomics.bed', 'w') as out_file:
    for line in f:
        columns = line.strip().split('\t')
        if columns[22].lower() in genes:  # Assuming gene names are in the second column
            out_file.write(line)

In [4]:
import pandas as pd

# Load the list of genes from the gene file
gene_file = 'Alzheimers.txt'
with open(gene_file, 'r') as f:
    gene_list = set(line.strip() for line in f)

# Load the data file into a pandas DataFrame
data_file = 'HMD_HumanPhenotype.csv'
data_df = pd.read_csv(data_file, sep=',', header=None)

# Filter the DataFrame for rows where the gene name in the first column matches the gene list
matched_df = data_df[data_df[0].isin(gene_list)]

# Select the first and third columns from the matched rows
result_df = matched_df[[2]]

# Save the result to a new file
result_file = 'matched_genes_alzheimers.tsv'
result_df.to_csv(result_file, sep='\t', index=False, header=False)

print(f'Matched genes and their third column details saved to {result_file}')

Matched genes and their third column details saved to matched_genes_alzheimers.tsv